run-general:
	go run cmd/general/main.go
run-hackerrank:
	go run cmd/hackerrank/main.go
run-leetcode:
	go run cmd/leetcode/main.go
run-ds:
	go run cmd/ds/main.go
run-algorithm:
	go run cmd/algorithm/main.go
